Repository Jyotibrat/AI-Flow, pull requests merged in 2025-08, with the labels that each got.

#10 Updated README with environment setup instructions
  .env.example
  .github/README.md
  server/.env.example
Labels: documentation, gssoc25, level1

#14 fix: enable Google login redirect and add AI Tools page (#5)
  src/components/AuthModal.tsx
  src/pages/AITools.tsx
  src/pages/AiToolsPage.tsx
Labels: bug, gssoc25, level2

#19 Fix: Mobile View Logo Overlap + Minor UI Improvements
  package-lock.json
  src/components/Header.tsx
  src/pages/AITools.tsx
  src/pages/Home.tsx
Labels: bug, gssoc25, level1

#34 Fix Scroll Position Issue on Page Navigation
  src/App.tsx
  src/components/ScrollToTop.tsx
Labels: bug, gssoc25, level1

#38 Fixed output editor that was not getting reset when switching between AI tools
  src/pages/AITools.tsx
Labels: bug, gssoc25, level2

#39 Fix blog card hover in dark mode and make card clickable
  src/pages/Blog.tsx
Labels: bug, gssoc25, level2
